# https://docs.travis-ci.com/user/ci-environment/
# Ubuntu 12.04 LTS Server Edition 64 bit
language: python
python:
-   "3.5"
install:
-   pip install ansible

script:
-   mv group_vars/testing_vars group_vars/all
-   sudo ansible-playbook -i hosts_local site.yml -vvvv
