- hosts: ECHALOASUERTE
  remote_user: root
  roles:
  - users
  - apache
  - { role: monitoring }
  - { role: echaloasuerte_django, datadir: "/data" }
  - { role: echaloasuerte_php, datadir: "/data" }
