---
# This apt_key may not be right
- apt_key:
    url: https://jenkins-ci.org/debian/jenkins-ci.org.key
    state: present
- apt_repository:
    repo: deb http://pkg.jenkins-ci.org/debian binary/
    state: present
- name: Install jenkins and curl, needed to configure jenkins
  apt:
    name: "{{ item }}"
    state: installed
    update-cache: yes
    force: yes
  with_items:
  - jenkins
  - curl
  - python-pip

- name: Install packages needed for running jobs
  pip:
    name: "{{ item }}"
  with_items:
  - ansible
  - pylint
  - coverage


- name: Generate random password for 'jenkins' user in /root/jkpass
  shell: openssl rand -base64 32 | tee /root/jkpass
  register: plain

- name: Encrypt the password
  shell: python -c 'import crypt; print crypt.crypt("{{ plain.stdout }}", "guest")'
  register: crypted

- name: Add user 'jenkins' to shadow group, and modify password
  user:
    name: jenkins
    shell: /bin/bash
    groups: shadow,sudo
    append: yes
    password: "{{ crypted.stdout }}"
  notify:
  - restart jenkins

- service:
    name: jenkins
    state: started


- name: Download jenkins client
  shell: wget https://ci.jenkins-ci.org/jnlpJars/jenkins-cli.jar -O /var/lib/jenkins/jenkins-cli.jar
  args:
    creates: /var/lib/jenkins/jenkins-cli.jar
  sudo: yes
  sudo_user: jenkins

- name: Install jobs
  copy:
    src: jobs/
    dest: /var/lib/jenkins/jobs
    owner: jenkins
    group: jenkins
  notify:
  - restart jenkins


- name: Create Jenkins updates folder.
  file:
    path: /var/lib/jenkins/updates
    owner: jenkins
    group: jenkins
    mode: 0755
    state: directory

- name: Update Jenkins plugin data.
  shell: >
    curl -L https://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /var/lib/jenkins/updates/default.json
  args:
    creates: /var/lib/jenkins/updates/default.json

- name: Permissions for default.json updates info.
  file:
    path: /var/lib/jenkins/updates/default.json
    owner: jenkins
    group: jenkins
    mode: 0755


- name: Wait for Jenkins to be available
  shell: java -jar /var/lib/jenkins/jenkins-cli.jar -s http://localhost:8080/ who-am-i --username jenkins --password-file /root/jkpass || java -jar /var/lib/jenkins/jenkins-cli.jar -s http://localhost:8080/ who-am-i
  register: result
  until: result.rc == 0
  retries: 10
  delay: 5

- name: Install Jenkins plugins.
  shell: >
    java -jar /var/lib/jenkins/jenkins-cli.jar -s http://localhost:8080/ install-plugin {{ item }} --username jenkins --password-file /root/jkpass || java -jar /var/lib/jenkins/jenkins-cli.jar -s http://localhost:8080/ install-plugin {{ item }}
  args:
    creates: /var/lib/jenkins/plugins/{{ item }}.jpi
  with_items:
  - git
  - embeddable-build-status
  - greenballs
  - cobertura
  - violations
  - github
  - role-strategy
  notify: restart jenkins

- name: Configure Jenkins (auth etc)
  copy:
    src: config.xml
    dest: /var/lib/jenkins/config.xml
    owner: jenkins
    group: jenkins
  notify:
  - restart jenkins
